const companySourceTypeEnum = [
  "url",
  "official_site",
  "recruiting",
  "public_registry",
  "financial_disclosure",
  "major_media",
  "user_memo",
  "model_knowledge",
] as const;

const confidenceEnum = ["high", "medium", "low"] as const;
const sourceTierEnum = ["primary", "public", "secondary", "user", "model"] as const;
const useRecommendationEnum = [
  "direct_use",
  "background_only",
  "use_with_caution",
  "do_not_use",
] as const;

export const companyResearchResponseJsonSchema = {
  type: "object",
  additionalProperties: false,
  required: [
    "researchId",
    "generatedAt",
    "companyName",
    "industry",
    "position",
    "accessMode",
    "confidence",
    "companyUnderstandingMemo",
    "identitySummary",
    "businessSummary",
    "financialHighlights",
    "recentDevelopments",
    "evidenceDigest",
    "sourceCoverage",
    "roleFitHypotheses",
    "esReviewFocus",
    "sources",
    "unknowns",
    "warnings",
  ],
  properties: {
    researchId: { type: "string" },
    generatedAt: { type: "string" },
    companyName: { type: "string" },
    industry: { type: "string" },
    position: { type: "string" },
    accessMode: {
      type: "string",
      enum: ["fetched_sources", "user_sources_only", "model_knowledge_only"],
    },
    confidence: { type: "string", enum: confidenceEnum },
    companyUnderstandingMemo: { type: "string" },
    identitySummary: {
      type: "object",
      additionalProperties: false,
      required: [
        "legalName",
        "jurisdiction",
        "entityKind",
        "corporateNumber",
        "headquarters",
        "industryClassification",
        "officialWebsite",
        "securitiesCode",
        "listingMarket",
      ],
      properties: {
        legalName: { type: "string" },
        jurisdiction: { type: "string" },
        entityKind: { type: "string" },
        corporateNumber: { type: "string" },
        headquarters: { type: "string" },
        industryClassification: { type: "string" },
        officialWebsite: { type: "string" },
        securitiesCode: { type: "string" },
        listingMarket: { type: "string" },
      },
    },
    businessSummary: { type: "array", items: { type: "string" } },
    financialHighlights: {
      type: "array",
      items: {
        type: "object",
        additionalProperties: false,
        required: ["label", "value", "period", "sourceId", "confidence"],
        properties: {
          label: { type: "string" },
          value: { type: "string" },
          period: { type: "string" },
          sourceId: { type: "string" },
          confidence: { type: "string", enum: confidenceEnum },
        },
      },
    },
    recentDevelopments: {
      type: "array",
      items: {
        type: "object",
        additionalProperties: false,
        required: [
          "title",
          "summary",
          "date",
          "sourceId",
          "sourceType",
          "esUseRecommendation",
          "riskNote",
          "url",
          "confidence",
        ],
        properties: {
          title: { type: "string" },
          summary: { type: "string" },
          date: { type: "string" },
          sourceId: { type: "string" },
          sourceType: { type: "string", enum: companySourceTypeEnum },
          esUseRecommendation: { type: "string", enum: useRecommendationEnum },
          riskNote: { type: "string" },
          url: { type: "string" },
          confidence: { type: "string", enum: confidenceEnum },
        },
      },
    },
    evidenceDigest: {
      type: "array",
      items: {
        type: "object",
        additionalProperties: false,
        required: [
          "category",
          "title",
          "summary",
          "sourceIds",
          "userRelevance",
          "useRecommendation",
          "riskNote",
        ],
        properties: {
          category: {
            type: "string",
            enum: [
              "public_registry",
              "official_company",
              "financial",
              "major_media",
              "user_context",
              "unverified",
            ],
          },
          title: { type: "string" },
          summary: { type: "string" },
          sourceIds: { type: "array", items: { type: "string" } },
          userRelevance: { type: "string" },
          useRecommendation: { type: "string", enum: useRecommendationEnum },
          riskNote: { type: "string" },
        },
      },
    },
    sourceCoverage: {
      type: "object",
      additionalProperties: false,
      required: [
        "publicRegistry",
        "official",
        "financial",
        "media",
        "userProvided",
        "modelKnowledge",
      ],
      properties: {
        publicRegistry: { type: "number" },
        official: { type: "number" },
        financial: { type: "number" },
        media: { type: "number" },
        userProvided: { type: "number" },
        modelKnowledge: { type: "number" },
      },
    },
    roleFitHypotheses: { type: "array", items: { type: "string" } },
    esReviewFocus: { type: "array", items: { type: "string" } },
    sources: {
      type: "array",
      items: {
        type: "object",
        additionalProperties: false,
        required: [
          "id",
          "title",
          "url",
          "sourceType",
          "sourceTier",
          "accessStatus",
          "usedFor",
          "excerpt",
        ],
        properties: {
          id: { type: "string" },
          title: { type: "string" },
          url: { type: "string" },
          sourceType: { type: "string", enum: companySourceTypeEnum },
          sourceTier: { type: "string", enum: sourceTierEnum },
          accessStatus: {
            type: "string",
            enum: ["fetched", "provided", "model_based", "failed"],
          },
          usedFor: { type: "array", items: { type: "string" } },
          excerpt: { type: "string" },
        },
      },
    },
    unknowns: { type: "array", items: { type: "string" } },
    warnings: {
      type: "array",
      items: {
        type: "object",
        additionalProperties: false,
        required: ["code", "message", "severity"],
        properties: {
          code: {
            type: "string",
            enum: [
              "insufficient_company_context",
              "insufficient_user_context",
              "possible_hallucination",
              "source_missing",
              "too_short",
              "too_long",
              "ambiguous_claim",
            ],
          },
          message: { type: "string" },
          severity: { type: "string", enum: ["info", "warning", "error"] },
        },
      },
    },
  },
} as const;
