export const reviewResponseJsonSchema = {
  type: "object",
  additionalProperties: false,
  required: [
    "reviewId",
    "generatedAt",
    "summary",
    "criterionReviews",
    "evidenceAudit",
    "suggestions",
    "userQuestions",
    "finalDraft",
    "sources",
    "warnings",
  ],
  properties: {
    reviewId: { type: "string" },
    generatedAt: { type: "string" },
    summary: {
      type: "object",
      additionalProperties: false,
      required: [
        "starRating",
        "headline",
        "overallComment",
        "strengths",
        "priorityFixes",
        "targetCompanyFitSummary",
      ],
      properties: {
        starRating: { type: "integer", enum: [1, 2, 3, 4, 5] },
        headline: { type: "string" },
        overallComment: { type: "string" },
        strengths: { type: "array", items: { type: "string" } },
        priorityFixes: { type: "array", items: { type: "string" } },
        targetCompanyFitSummary: { type: "string" },
      },
    },
    criterionReviews: {
      type: "array",
      minItems: 5,
      maxItems: 5,
      items: {
        type: "object",
        additionalProperties: false,
        required: ["criterion", "starRating", "comment", "strengths", "weaknesses"],
        properties: {
          criterion: {
            type: "string",
            enum: [
              "logical_structure",
              "specificity_and_original_experience",
              "company_understanding_and_fit",
              "expression_quality",
              "authenticity_and_ai_likeness",
            ],
          },
          starRating: { type: "integer", enum: [1, 2, 3, 4, 5] },
          comment: { type: "string" },
          strengths: { type: "array", items: { type: "string" } },
          weaknesses: { type: "array", items: { type: "string" } },
        },
      },
    },
    evidenceAudit: {
      type: "array",
      minItems: 1,
      items: {
        type: "object",
        additionalProperties: false,
        required: [
          "id",
          "claimText",
          "status",
          "verificationStatus",
          "confidence",
          "sourceQuality",
          "checkedBy",
          "assessment",
          "evidence",
          "caution",
          "userCheckRequired",
        ],
        properties: {
          id: { type: "string" },
          claimText: { type: "string" },
          status: {
            type: "string",
            enum: [
              "supported",
              "weakly_supported",
              "unsupported",
              "possibly_inaccurate",
              "needs_user_confirmation",
            ],
          },
          verificationStatus: {
            type: "string",
            enum: [
              "verified_by_source",
              "partially_verified",
              "unverified",
              "conflicting_sources",
              "needs_user_confirmation",
            ],
          },
          confidence: { type: "string", enum: ["high", "medium", "low"] },
          sourceQuality: {
            type: "string",
            enum: [
              "official",
              "company_provided",
              "user_provided",
              "third_party",
              "model_knowledge",
              "unknown",
            ],
          },
          checkedBy: {
            type: "object",
            additionalProperties: false,
            required: ["research", "verifier", "reviewer"],
            properties: {
              research: { type: "boolean" },
              verifier: { type: "boolean" },
              reviewer: { type: "boolean" },
            },
          },
          assessment: { type: "string" },
          evidence: { type: "array", items: { $ref: "#/$defs/evidenceReference" } },
          caution: { type: "string" },
          userCheckRequired: { type: "boolean" },
        },
      },
    },
    suggestions: {
      type: "array",
      minItems: 1,
      maxItems: 8,
      items: {
        type: "object",
        additionalProperties: false,
        required: [
          "id",
          "type",
          "severity",
          "title",
          "targetText",
          "problem",
          "suggestedRevision",
          "rationale",
          "expectedImpact",
          "evidence",
          "userConfirmationNeeded",
          "diffHint",
        ],
        properties: {
          id: { type: "string" },
          type: {
            type: "string",
            enum: ["logic", "specificity", "company_fit", "expression", "authenticity", "length"],
          },
          severity: { type: "string", enum: ["high", "medium", "low"] },
          title: { type: "string" },
          targetText: { type: "string" },
          problem: { type: "string" },
          suggestedRevision: { type: "string" },
          rationale: { type: "string" },
          expectedImpact: { type: "string" },
          evidence: { type: "array", items: { $ref: "#/$defs/evidenceReference" } },
          userConfirmationNeeded: { type: "array", items: { type: "string" } },
          diffHint: {
            type: "object",
            additionalProperties: false,
            required: ["before", "after", "changeSummary"],
            properties: {
              before: { type: "string" },
              after: { type: "string" },
              changeSummary: { type: "string" },
            },
          },
        },
      },
    },
    userQuestions: {
      type: "array",
      items: {
        type: "object",
        additionalProperties: false,
        required: ["id", "question", "reason", "relatedSuggestionIds"],
        properties: {
          id: { type: "string" },
          question: { type: "string" },
          reason: { type: "string" },
          relatedSuggestionIds: { type: "array", items: { type: "string" } },
        },
      },
    },
    finalDraft: {
      type: "object",
      additionalProperties: false,
      required: ["text", "characterCount", "notes"],
      properties: {
        text: { type: "string" },
        characterCount: { type: "integer" },
        notes: { type: "array", items: { type: "string" } },
      },
    },
    sources: {
      type: "array",
      items: {
        type: "object",
        additionalProperties: false,
        required: ["id", "title", "url", "sourceType", "usedFor"],
        properties: {
          id: { type: "string" },
          title: { type: "string" },
          url: { type: "string" },
          sourceType: { type: "string", enum: ["url", "user_memo", "model_knowledge"] },
          usedFor: { type: "array", items: { type: "string" } },
        },
      },
    },
    warnings: {
      type: "array",
      items: {
        type: "object",
        additionalProperties: false,
        required: ["code", "message", "severity"],
        properties: {
          code: {
            type: "string",
            enum: [
              "insufficient_company_context",
              "insufficient_user_context",
              "possible_hallucination",
              "source_missing",
              "too_short",
              "too_long",
              "ambiguous_claim",
            ],
          },
          message: { type: "string" },
          severity: { type: "string", enum: ["info", "warning", "error"] },
        },
      },
    },
  },
  $defs: {
    evidenceReference: {
      type: "object",
      additionalProperties: false,
      required: [
        "sourceId",
        "sourceTitle",
        "url",
        "quotedOrParaphrasedEvidence",
        "reliability",
        "supportsClaim",
        "sourceQuality",
      ],
      properties: {
        sourceId: { type: "string" },
        sourceTitle: { type: "string" },
        url: { type: "string" },
        quotedOrParaphrasedEvidence: { type: "string" },
        reliability: { type: "string", enum: ["high", "medium", "low", "user_provided"] },
        supportsClaim: { type: "boolean" },
        sourceQuality: {
          type: "string",
          enum: [
            "official",
            "company_provided",
            "user_provided",
            "third_party",
            "model_knowledge",
            "unknown",
          ],
        },
      },
    },
  },
} as const;
